name: Pull Request

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install deps
        run: |
          python3 -m pip install --upgrade build

      - name: Build and install package
        run: |
          python3 -m build
          python3 -m pip install ./dist/*.whl

      - name: Test
        working-directory: ./tests 
        run: |
          python3 -m unittest discover
          